//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_address
    {
        public int a_id { get; set; }
        public Nullable<System.Guid> a_guid { get; set; }
        public Nullable<System.DateTime> a_indate { get; set; }
        public string a_own { get; set; }
        public string a_owncompany { get; set; }
        public System.Guid a_ownid { get; set; }
        public string a_sheng { get; set; }
        public string a_shi { get; set; }
        public string a_qu { get; set; }
        public string a_jiedao { get; set; }
        public string a_mob { get; set; }
        public string a_lxr { get; set; }
        public string a_pc { get; set; }
        public string a_telqu { get; set; }
        public string a_tel { get; set; }
        public string a_telfen { get; set; }
    }
}
