//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ad_setting
    {
        public long as_id { get; set; }
        public Nullable<System.Guid> as_guid { get; set; }
        public string as_channel { get; set; }
        public string as_region { get; set; }
        public string as_desc { get; set; }
    }
}
