//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ad
    {
        public long ad_id { get; set; }
        public Nullable<System.Guid> ad_guid { get; set; }
        public Nullable<System.DateTime> ad_indate { get; set; }
        public string ad_inputer { get; set; }
        public System.Guid ad_inputerid { get; set; }
        public Nullable<System.Guid> ad_setid { get; set; }
        public string ad_channel { get; set; }
        public string ad_regrion { get; set; }
        public string ad_memo { get; set; }
        public Nullable<int> ad_index { get; set; }
        public string ad_pic { get; set; }
        public string ad_link { get; set; }
        public string ad_title { get; set; }
        public bool ad_show { get; set; }
        public System.DateTime ad_expires { get; set; }
    }
}
