//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_agreement_agent
    {
        public long aa_id { get; set; }
        public Nullable<System.Guid> aa_guid { get; set; }
        public Nullable<System.Guid> aa_flowid { get; set; }
        public Nullable<System.DateTime> aa_indate { get; set; }
        public string aa_company { get; set; }
        public string aa_companyEng { get; set; }
        public System.Guid aa_ent_id { get; set; }
        public string aa_status { get; set; }
        public string aa_reason { get; set; }
        public Nullable<int> aa_status_index { get; set; }
    }
}
