//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_agreement_pay
    {
        public long ap_id { get; set; }
        public Nullable<System.Guid> ap_guid { get; set; }
        public Nullable<System.Guid> ap_flowid { get; set; }
        public Nullable<System.DateTime> ap_indate { get; set; }
        public string ap_company { get; set; }
        public string ap_companyEng { get; set; }
        public System.Guid ap_ent_id { get; set; }
        public string ap_order_code { get; set; }
        public System.Guid ap_order_id { get; set; }
        public string ap_sinotexAdd { get; set; }
        public string ap_sinotexRecipient { get; set; }
        public string ap_sinotexTel { get; set; }
        public string ap_carrier { get; set; }
        public string ap_tracknum { get; set; }
        public string ap_status { get; set; }
        public string ap_reason { get; set; }
        public Nullable<int> ap_status_color { get; set; }
        public Nullable<int> ap_status_index { get; set; }
    }
}
