//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_anonymous
    {
        public int ol_id { get; set; }
        public Nullable<System.Guid> ol_guid { get; set; }
        public Nullable<System.DateTime> ol_indate { get; set; }
        public string ol_username { get; set; }
        public System.Guid ol_usrid { get; set; }
        public string ol_rename { get; set; }
        public string ol_company { get; set; }
        public string ol_role { get; set; }
        public Nullable<System.Guid> ol_roldid { get; set; }
        public string ol_ip { get; set; }
        public string ol_agent { get; set; }
        public string ol_referer { get; set; }
        public string ol_visitpage { get; set; }
    }
}
