//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_app_log
    {
        public long al_id { get; set; }
        public Nullable<System.Guid> al_guid { get; set; }
        public Nullable<System.DateTime> al_indate { get; set; }
        public string al_ip { get; set; }
        public string al_ipsource { get; set; }
        public string al_model { get; set; }
        public string al_system { get; set; }
        public string al_system_ver { get; set; }
        public string al_app_ver { get; set; }
        public string al_resolution { get; set; }
        public string al_usrname { get; set; }
        public Nullable<bool> al_logon { get; set; }
        public string al_coordinate { get; set; }
        public string al_location { get; set; }
        public string al_tel { get; set; }
        public string al_imei { get; set; }
        public string al_sp { get; set; }
        public string al_token { get; set; }
    }
}
