//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_buglst
    {
        public long b_id { get; set; }
        public Nullable<System.Guid> b_guid { get; set; }
        public Nullable<System.DateTime> b_indate { get; set; }
        public string b_inputer { get; set; }
        public System.Guid b_inputerid { get; set; }
        public string b_title { get; set; }
        public string b_url { get; set; }
        public string b_browser { get; set; }
        public string b_type { get; set; }
        public string b_category { get; set; }
        public string b_loginRole { get; set; }
        public string b_snap { get; set; }
        public Nullable<bool> b_ischance { get; set; }
        public string b_Importance { get; set; }
        public string b_steps { get; set; }
        public Nullable<System.DateTime> b_fixed { get; set; }
        public string b_fixer { get; set; }
        public Nullable<System.Guid> b_fixerid { get; set; }
        public string b_fixproc { get; set; }
        public Nullable<bool> b_fixing { get; set; }
        public Nullable<bool> b_close { get; set; }
        public Nullable<System.DateTime> b_tested { get; set; }
        public string b_tester { get; set; }
        public Nullable<System.Guid> b_testerId { get; set; }
        public string b_testing { get; set; }
        public string b_testing_snap { get; set; }
    }
}
