//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Channel
    {
        public int ch_ChannelID { get; set; }
        public Nullable<System.Guid> ch_GUID { get; set; }
        public Nullable<System.DateTime> ch_InDate { get; set; }
        public string ch_Inputer { get; set; }
        public System.Guid ch_InputerID { get; set; }
        public string ch_Title { get; set; }
        public Nullable<System.DateTime> ch_UpdateDate { get; set; }
        public string ch_UpdateUser { get; set; }
        public Nullable<System.Guid> ch_UpdateUserID { get; set; }
        public Nullable<int> ch_LanguageType { get; set; }
    }
}
