//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_customs_fee
    {
        public int cf_id { get; set; }
        public Nullable<System.Guid> cf_guid { get; set; }
        public Nullable<System.DateTime> cf_indate { get; set; }
        public string cf_inputer { get; set; }
        public System.Guid cf_inputerId { get; set; }
        public string cf_port { get; set; }
        public string cf_type { get; set; }
        public decimal cf_fee { get; set; }
        public string cf_memo { get; set; }
    }
}
