//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_dict
    {
        public int d_id { get; set; }
        public Nullable<System.Guid> d_guid { get; set; }
        public Nullable<System.DateTime> d_indate { get; set; }
        public string d_inputer { get; set; }
        public System.Guid d_inputerid { get; set; }
        public string d_page { get; set; }
        public string d_chinese { get; set; }
        public string d_english { get; set; }
    }
}
