//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_emblem_setting
    {
        public long ic_id { get; set; }
        public Nullable<System.Guid> ic_guid { get; set; }
        public Nullable<System.DateTime> ic_indate { get; set; }
        public string ic_title { get; set; }
        public string ic_titleEng { get; set; }
        public string ic_bigicon { get; set; }
        public decimal ic_weight { get; set; }
        public decimal ic_classMultiple { get; set; }
        public string ic_memo { get; set; }
        public string ic_memoEng { get; set; }
        public string ic_inputer { get; set; }
        public System.Guid ic_inputerid { get; set; }
    }
}
