//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_events
    {
        public int ev_id { get; set; }
        public Nullable<System.Guid> ev_guid { get; set; }
        public Nullable<System.DateTime> ev_indate { get; set; }
        public string ev_title { get; set; }
        public string ev_subtitle { get; set; }
        public string ev_PageKeywords { get; set; }
        public string ev_PageDescription { get; set; }
        public int ev_count { get; set; }
    }
}
