//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_event_signup
    {
        public int s_id { get; set; }
        public Nullable<System.Guid> s_guid { get; set; }
        public Nullable<System.DateTime> s_indate { get; set; }
        public string s_title { get; set; }
        public System.Guid s_title_id { get; set; }
        public string s_company { get; set; }
        public Nullable<int> s_num { get; set; }
        public string s_lxr { get; set; }
        public string s_mob { get; set; }
        public string s_tel { get; set; }
        public string s_add { get; set; }
        public string s_comtype { get; set; }
    }
}
