//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_exchange_records
    {
        public int eh_id { get; set; }
        public Nullable<System.Guid> eh_guid { get; set; }
        public System.DateTime eh_startdate { get; set; }
        public Nullable<System.DateTime> en_enddate { get; set; }
        public string eh_type { get; set; }
        public decimal eh_rate { get; set; }
        public string eh_inputer { get; set; }
        public System.Guid eh_inputerid { get; set; }
    }
}
