//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_FriendGroup
    {
        public int fg_FriendGroupID { get; set; }
        public Nullable<System.Guid> fg_GUID { get; set; }
        public Nullable<System.DateTime> fg_InDate { get; set; }
        public string fg_Title { get; set; }
        public string fg_Inputer { get; set; }
        public System.Guid fg_InputerID { get; set; }
        public string fg_Description { get; set; }
        public Nullable<System.DateTime> fg_UpdateDate { get; set; }
        public string fg_UpdateUser { get; set; }
        public Nullable<System.Guid> fg_UpdateUserID { get; set; }
        public Nullable<int> fg_LanguageType { get; set; }
    }
}
