//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_friendIndex
    {
        public long f_id { get; set; }
        public Nullable<System.Guid> f_guid { get; set; }
        public Nullable<System.DateTime> f_indate { get; set; }
        public string f_own { get; set; }
        public string f_owncompany { get; set; }
        public System.Guid f_ownid { get; set; }
        public System.Guid f_entid { get; set; }
        public string f_group { get; set; }
        public string f_memo { get; set; }
        public string f_type { get; set; }
        public Nullable<System.Guid> f_FriendGroupID { get; set; }
        public Nullable<int> t_LanguageType { get; set; }
    }
}
