//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_guestBook
    {
        public int gb_id { get; set; }
        public System.Guid gb_guid { get; set; }
        public Nullable<System.DateTime> gb_indate { get; set; }
        public string gb_content { get; set; }
        public string gb_tel { get; set; }
        public string gb_ip { get; set; }
    }
}
