//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_importtariff_items
    {
        public int it_id { get; set; }
        public System.Guid it_guid { get; set; }
        public string it_No { get; set; }
        public string it_TFN { get; set; }
        public string it_productName { get; set; }
        public string it_productCount { get; set; }
        public string it_unit { get; set; }
        public decimal it_dutiablePrice { get; set; }
        public string it_taxRate { get; set; }
        public decimal it_taxAmount { get; set; }
    }
}
