//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_importtariff
    {
        public int i_id { get; set; }
        public System.Guid i_guid { get; set; }
        public System.Guid o_guid { get; set; }
        public string o_code { get; set; }
        public string i_ip { get; set; }
        public string i_port { get; set; }
        public System.DateTime i_indate { get; set; }
        public string i_logisticsCompany { get; set; }
        public string i_incomeSystem { get; set; }
        public System.DateTime i_time { get; set; }
        public string i_No { get; set; }
        public string i_office { get; set; }
        public string i_project { get; set; }
        public string i_budgetaryLevel { get; set; }
        public string i_recipientTreasury { get; set; }
        public string i_payName { get; set; }
        public string i_payAccount { get; set; }
        public string i_bank { get; set; }
        public decimal i_rmbMoney { get; set; }
        public string i_exchangeRate { get; set; }
        public string i_rmbUMoney { get; set; }
        public string i_unitNo { get; set; }
        public string i_declarationNo { get; set; }
        public string i_approvalNo { get; set; }
        public string i_transportNo { get; set; }
        public string i_deadline { get; set; }
        public string i_loadingNo { get; set; }
        public string i_GBCode { get; set; }
        public string i_EPTransaction { get; set; }
        public string i_filepath { get; set; }
    }
}
