//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_importdeclaration_items
    {
        public int it_id { get; set; }
        public System.Guid it_guid { get; set; }
        public string i_customsNo { get; set; }
        public decimal it_unitPrice { get; set; }
        public decimal it_totalPrice { get; set; }
        public string it_monetarySystem { get; set; }
        public string it_itemNo { get; set; }
        public string it_productNo { get; set; }
        public string it_productName { get; set; }
        public string it_productType { get; set; }
        public string it_productNumber { get; set; }
        public string it_country { get; set; }
        public string it_exemption { get; set; }
    }
}
