//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_importdeclaration
    {
        public int i_id { get; set; }
        public System.Guid i_guid { get; set; }
        public System.Guid o_guid { get; set; }
        public string o_code { get; set; }
        public string i_ip { get; set; }
        public string i_port { get; set; }
        public System.DateTime i_indate { get; set; }
        public string i_logisticsCompany { get; set; }
        public string i_declarationNo { get; set; }
        public string i_customsNo { get; set; }
        public string i_importPort { get; set; }
        public System.DateTime i_importDate { get; set; }
        public string i_unitOpeartion { get; set; }
        public string i_deliveryNumber { get; set; }
        public string i_consignee { get; set; }
        public string i_transactionMode { get; set; }
        public string i_originCountry { get; set; }
        public string i_destination { get; set; }
        public string i_grossWeight { get; set; }
        public string i_netWeight { get; set; }
        public string i_containerNo { get; set; }
        public string i_ICP { get; set; }
        public Nullable<System.DateTime> i_declarationDate { get; set; }
        public string i_transportMode { get; set; }
        public string i_exemption { get; set; }
        public string i_licenseKey { get; set; }
        public string i_shipment { get; set; }
        public string i_approvalNumber { get; set; }
        public string i_diveryTerms { get; set; }
        public string i_fare { get; set; }
        public string i_premuim { get; set; }
        public string i_extras { get; set; }
        public string i_contracNo { get; set; }
        public Nullable<int> i_packageNum { get; set; }
        public string i_packageKind { get; set; }
        public string i_documentsAttached { get; set; }
        public string i_remarks { get; set; }
        public string i_situation { get; set; }
        public string i_dataEntry { get; set; }
        public string i_inputUnit { get; set; }
        public string i_declarant { get; set; }
        public string i_address { get; set; }
        public string i_zipcode { get; set; }
        public string i_telephone { get; set; }
        public string i_filepath { get; set; }
    }
}
