//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_invoice
    {
        public int inv_id { get; set; }
        public Nullable<System.Guid> inv_guid { get; set; }
        public System.DateTime inv_indate { get; set; }
        public string inv_own { get; set; }
        public string inv_comnay { get; set; }
        public System.Guid inv_ownid { get; set; }
        public string inv_name { get; set; }
        public string inv_taxcode { get; set; }
        public string inv_bank { get; set; }
        public string inv_bankno { get; set; }
        public string inv_add { get; set; }
        public string inv_tel { get; set; }
    }
}
