//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Inquiry_Config
    {
        public int Cfg_Id { get; set; }
        public string Cfg_Key { get; set; }
        public string Cfg_Value { get; set; }
        public System.DateTime Cfg_CreateDate { get; set; }
        public decimal Cfg_OrderNo { get; set; }
    }
}
