//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_inbox
    {
        public long ib_id { get; set; }
        public Nullable<System.Guid> ib_guid { get; set; }
        public Nullable<System.DateTime> ib_indate { get; set; }
        public string ib_sender { get; set; }
        public string ib_senderEng { get; set; }
        public string ib_senderCom { get; set; }
        public string ib_senderComEng { get; set; }
        public System.Guid ib_senderid { get; set; }
        public string ib_receiver { get; set; }
        public string ib_receiverEng { get; set; }
        public string ib_receiverCom { get; set; }
        public string ib_receiverComEng { get; set; }
        public System.Guid ib_receiverid { get; set; }
        public Nullable<bool> ib_nmark { get; set; }
        public string ib_subject { get; set; }
        public string ib_msg { get; set; }
        public Nullable<short> ib_boxtype { get; set; }
        public Nullable<short> ib_msgtype { get; set; }
    }
}
