//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Inquiry_Apply
    {
        public System.Guid Apply_Id { get; set; }
        public string Apply_Code { get; set; }
        public System.DateTime Apply_Date { get; set; }
        public Nullable<System.DateTime> Apply_LastModiDate { get; set; }
        public System.Guid Apply_CreaterId { get; set; }
        public string Apply_ProChengFen { get; set; }
        public string Apply_ProShaZhi { get; set; }
        public int Apply_ProGuShu { get; set; }
        public string Apply_ProChengShaSheBei { get; set; }
        public string Apply_ProShuMiangy { get; set; }
        public string Apply_ProYongtu { get; set; }
        public string Apply_ProPeiMian { get; set; }
        public string Apply_ProClass { get; set; }
        public string Apply_ProPlace { get; set; }
        public string Apply_ProCountry { get; set; }
        public string Apply_ProMianLiao { get; set; }
        public string Apply_ProFinalProduct { get; set; }
        public string Apply_ProTargetMarket { get; set; }
        public decimal AppLy_Quantity { get; set; }
        public string AppLy_Pro_GuiType { get; set; }
        public string AppLy_SupplyType { get; set; }
        public string AppLy_TradeMode { get; set; }
        public System.DateTime AppLy_ExpiryDate { get; set; }
        public string AppLy_Status { get; set; }
        public string AppLy_RejectReason { get; set; }
        public Nullable<System.Guid> AppLy_AuditUser { get; set; }
        public Nullable<System.DateTime> AppLy_AuditDate { get; set; }
        public int Apply_CollectionNum { get; set; }
        public int Apply_OfferNum { get; set; }
        public bool Apply_bDel { get; set; }
        public bool Apply_bTrash { get; set; }
    }
}
