//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_lc_Sheet
    {
        public int ls_id { get; set; }
        public Nullable<System.Guid> ls_guid { get; set; }
        public Nullable<System.DateTime> ls_indate { get; set; }
        public string ls_inputer { get; set; }
        public System.Guid ls_inputerid { get; set; }
        public string ls_title { get; set; }
        public string ls_next { get; set; }
    }
}
