//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_lc_setting
    {
        public int lc_id { get; set; }
        public Nullable<System.Guid> lc_guid { get; set; }
        public Nullable<System.DateTime> lc_indate { get; set; }
        public string lc_inputer { get; set; }
        public System.Guid lc_inputerId { get; set; }
        public string lc_type { get; set; }
        public int lc_days { get; set; }
        public string lc_style { get; set; }
    }
}
