//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_lc_Rate
    {
        public long r_id { get; set; }
        public Nullable<System.Guid> r_guid { get; set; }
        public Nullable<System.DateTime> r_indate { get; set; }
        public string r_ownCom { get; set; }
        public string r_ownComEng { get; set; }
        public System.Guid r_ownComId { get; set; }
        public string r_clientCom { get; set; }
        public string r_clientComEng { get; set; }
        public System.Guid r_clientComId { get; set; }
        public decimal r_rate { get; set; }
        public string r_memo { get; set; }
        public string r_inputer { get; set; }
        public System.Guid r_inputerid { get; set; }
        public Nullable<int> r_sort { get; set; }
    }
}
