//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_log
    {
        public long lg_id { get; set; }
        public Nullable<System.Guid> lg_guid { get; set; }
        public Nullable<System.DateTime> lg_indate { get; set; }
        public string lg_sender { get; set; }
        public string lg_part { get; set; }
        public string lg_msg { get; set; }
        public string lg_stat { get; set; }
    }
}
