//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_messageJobs
    {
        public long mj_id { get; set; }
        public Nullable<System.Guid> mj_guid { get; set; }
        public Nullable<System.DateTime> mj_indate { get; set; }
        public string mj_inputer { get; set; }
        public System.Guid mj_inputerid { get; set; }
        public Nullable<bool> mj_sendMail { get; set; }
        public Nullable<bool> mj_sendSms { get; set; }
        public Nullable<bool> mj_sendInbox { get; set; }
        public Nullable<System.DateTime> mj_startDate { get; set; }
        public string mj_subject { get; set; }
        public string mj_message { get; set; }
        public string mj_roles { get; set; }
        public string mj_usrid { get; set; }
        public Nullable<System.DateTime> mj_endDate { get; set; }
        public string mj_stat { get; set; }
        public string mj_statMessage { get; set; }
        public Nullable<int> mj_ok { get; set; }
        public Nullable<int> mj_error { get; set; }
        public string mj_type { get; set; }
    }
}
