//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_message
    {
        public long ms_id { get; set; }
        public Nullable<System.Guid> ms_guid { get; set; }
        public Nullable<System.DateTime> ms_indate { get; set; }
        public string ms_sender { get; set; }
        public string ms_senderEng { get; set; }
        public string ms_senderCom { get; set; }
        public string ms_senderComEng { get; set; }
        public System.Guid ms_senderid { get; set; }
        public string ms_receiver { get; set; }
        public string ms_receiverEng { get; set; }
        public string ms_receiverCom { get; set; }
        public string ms_receiverComEng { get; set; }
        public System.Guid ms_receiverid { get; set; }
        public Nullable<bool> ms_nmark { get; set; }
        public string ms_msg { get; set; }
        public string ms_msgReceive { get; set; }
        public string ms_Image { get; set; }
        public string ms_type { get; set; }
        public string ms_ImageThumb { get; set; }
        public Nullable<int> ms_Src { get; set; }
    }
}
