//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_msg_sc
    {
        public int sc_id { get; set; }
        public Nullable<System.Guid> sc_guid { get; set; }
        public string sc_typechn { get; set; }
        public string sc_typeeng { get; set; }
        public string sc_chinese { get; set; }
        public string sc_english { get; set; }
        public string sc_role { get; set; }
        public System.DateTime sc_indate { get; set; }
        public Nullable<bool> sc_enabled { get; set; }
        public string sc_inputer { get; set; }
        public System.Guid sc_inputerid { get; set; }
    }
}
