//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_pay_info
    {
        public long pay_id { get; set; }
        public Nullable<System.Guid> pay_guid { get; set; }
        public System.Guid pay_orderid { get; set; }
        public string pay_platform { get; set; }
        public string pay_sn { get; set; }
        public System.DateTime pay_date { get; set; }
        public decimal pay_price { get; set; }
    }
}
