//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_page
    {
        public long pa_id { get; set; }
        public Nullable<System.Guid> pa_guid { get; set; }
        public System.DateTime pa_indate { get; set; }
        public string pa_inputer { get; set; }
        public System.Guid pa_inputerid { get; set; }
        public string pa_channel { get; set; }
        public string pa_title { get; set; }
        public string pa_subtitle { get; set; }
        public string pa_link { get; set; }
        public string pa_content { get; set; }
        public Nullable<bool> pa_show { get; set; }
        public Nullable<int> pa_sort { get; set; }
        public Nullable<System.Guid> pa_channelID { get; set; }
    }
}
