//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_pay_log
    {
        public long pl_id { get; set; }
        public System.Guid pl_guid { get; set; }
        public Nullable<System.DateTime> pl_indate { get; set; }
        public System.Guid pl_orderid { get; set; }
        public string pl_bankid { get; set; }
        public string pl_bankOption { get; set; }
        public Nullable<decimal> pl_price { get; set; }
        public string pl_activity { get; set; }
        public string pl_op { get; set; }
        public System.Guid pl_opid { get; set; }
        public string pl_opip { get; set; }
        public string pl_opport { get; set; }
        public bool pl_ok { get; set; }
        public string pl_interface { get; set; }
        public string pl_return { get; set; }
        public string pl_returnIp { get; set; }
        public string pl_returnport { get; set; }
        public Nullable<System.DateTime> pl_returnDate { get; set; }
        public Nullable<System.DateTime> pl_PayDate { get; set; }
    }
}
