//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Permission
    {
        public long le_id { get; set; }
        public Nullable<System.Guid> le_guid { get; set; }
        public Nullable<System.Guid> le_usrguid { get; set; }
        public string le_role { get; set; }
        public System.Guid le_rgid { get; set; }
    }
}
