//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_platform_collectmenu
    {
        public long pf_id { get; set; }
        public Nullable<System.Guid> pf_guid { get; set; }
        public string pf_op { get; set; }
        public System.Guid pf_opid { get; set; }
        public System.Guid pf_menuid { get; set; }
    }
}
