//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_platform_menu
    {
        public int pa_id { get; set; }
        public System.Guid pa_guid { get; set; }
        public Nullable<System.DateTime> pa_indate { get; set; }
        public string pa_inputer { get; set; }
        public System.Guid pa_inputerid { get; set; }
        public System.Guid pa_typeid { get; set; }
        public string pa_title { get; set; }
        public string pa_area { get; set; }
        public string pa_controller { get; set; }
        public string pa_action { get; set; }
        public string pa_url { get; set; }
        public int pa_index { get; set; }
    }
}
