//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_platform_menutype
    {
        public int mt_id { get; set; }
        public Nullable<System.Guid> mt_guid { get; set; }
        public Nullable<System.DateTime> mt_indate { get; set; }
        public string mt_inputer { get; set; }
        public Nullable<System.Guid> mt_inputerid { get; set; }
        public int mt_index { get; set; }
        public string mt_type { get; set; }
    }
}
