//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_product
    {
        public int p_id { get; set; }
        public Nullable<System.Guid> p_guid { get; set; }
        public Nullable<System.DateTime> p_indate { get; set; }
        public string p_inputer { get; set; }
        public System.Guid p_inputerid { get; set; }
        public string p_company { get; set; }
        public string p_companyEng { get; set; }
        public System.Guid p_companyid { get; set; }
        public string p_lxr { get; set; }
        public string p_lxrEng { get; set; }
        public string p_pic { get; set; }
        public Nullable<int> p_clk { get; set; }
        public Nullable<int> p_buyCount { get; set; }
        public Nullable<int> p_type_id { get; set; }
        public string p_type { get; set; }
        public string p_chengfen { get; set; }
        public string p_Chandi { get; set; }
        public string p_shipPort { get; set; }
        public string p_Brand { get; set; }
        public string p_Yongtu { get; set; }
        public string p_shumiangy { get; set; }
        public string p_chengshashebei { get; set; }
        public string p_shazhi { get; set; }
        public string p_gushu { get; set; }
        public string p_class { get; set; }
        public string p_ActualCount { get; set; }
        public string p_CountCV { get; set; }
        public string p_CLSP { get; set; }
        public string p_StengthCV { get; set; }
        public string p_syscn { get; set; }
        public string p_TPI { get; set; }
        public string p_U { get; set; }
        public string p_Thin { get; set; }
        public string p_Thick { get; set; }
        public string p_IPI { get; set; }
        public string p_mj200 { get; set; }
        public string p_mj280 { get; set; }
        public Nullable<decimal> p_Price { get; set; }
        public string p_PriceUnit { get; set; }
        public System.DateTime p_youxiaoDate { get; set; }
        public string p_zhuangchuanDate { get; set; }
        public Nullable<decimal> p_packs { get; set; }
        public Nullable<int> p_packnum { get; set; }
        public Nullable<int> p_packe { get; set; }
        public Nullable<decimal> p_gonghuos { get; set; }
        public string p_xiang { get; set; }
        public string p_guitype { get; set; }
        public Nullable<int> p_gonghuoe { get; set; }
        public string p_memo { get; set; }
        public Nullable<int> p_sort { get; set; }
        public Nullable<int> p_tuijian { get; set; }
        public Nullable<bool> p_menutj { get; set; }
        public Nullable<bool> p_top { get; set; }
        public Nullable<byte> p_stat { get; set; }
        public string p_statText { get; set; }
        public string p_statReason { get; set; }
        public string p_sh_sheng { get; set; }
        public string p_sh_shi { get; set; }
        public string p_sh_qu { get; set; }
        public string p_sh_jiedao { get; set; }
        public string p_sh_lxr { get; set; }
        public string p_sh_mob { get; set; }
        public string p_sh_pc { get; set; }
        public string p_sh_telqu { get; set; }
        public string p_sh_tel { get; set; }
        public string p_sh_telfen { get; set; }
        public string p_fahuodi { get; set; }
        public Nullable<decimal> p_yufukuan { get; set; }
        public Nullable<bool> p_hanshui { get; set; }
        public Nullable<decimal> p_netweight { get; set; }
        public Nullable<decimal> p_boxweight { get; set; }
    }
}
