//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Qc
    {
        public long q_id { get; set; }
        public Nullable<System.Guid> q_guid { get; set; }
        public Nullable<System.Guid> q_flowid { get; set; }
        public System.DateTime q_redate { get; set; }
        public Nullable<System.DateTime> q_checkDate { get; set; }
        public System.Guid q_order_id { get; set; }
        public string q_order_code { get; set; }
        public string q_checker { get; set; }
        public string q_checker_eng { get; set; }
        public Nullable<System.Guid> q_checker_guid { get; set; }
        public string q_check_lxr { get; set; }
        public string q_check_lxr_eng { get; set; }
        public string q_check_tel { get; set; }
        public string q_check_mob { get; set; }
        public string q_check_add { get; set; }
        public string q_check_add_eng { get; set; }
        public string q_check_fw { get; set; }
        public string q_region { get; set; }
        public string q_enterprise { get; set; }
        public string q_enterprise_eng { get; set; }
        public System.Guid q_ent_guid { get; set; }
        public string q_checkadd { get; set; }
        public string q_lianxiren { get; set; }
        public string q_tel { get; set; }
        public Nullable<bool> q_result { get; set; }
        public string q_status { get; set; }
        public string q_reason { get; set; }
        public Nullable<decimal> q_ac { get; set; }
        public Nullable<decimal> q_cv { get; set; }
        public Nullable<decimal> q_scv { get; set; }
        public Nullable<decimal> q_ipi { get; set; }
        public Nullable<decimal> q_tpi { get; set; }
        public Nullable<decimal> q_hcl { get; set; }
        public Nullable<decimal> q_u { get; set; }
        public Nullable<decimal> q_thin { get; set; }
        public Nullable<decimal> q_thick { get; set; }
        public Nullable<decimal> q_clsp { get; set; }
        public Nullable<decimal> q_sys { get; set; }
        public Nullable<decimal> q_neps200 { get; set; }
        public Nullable<decimal> q_neps280 { get; set; }
        public Nullable<bool> q_finish { get; set; }
        public Nullable<decimal> q_s_ac { get; set; }
        public Nullable<decimal> q_s_u { get; set; }
        public Nullable<decimal> q_s_clsp { get; set; }
        public Nullable<decimal> q_s_sys { get; set; }
        public Nullable<decimal> q_d_ac { get; set; }
        public Nullable<decimal> q_d_u { get; set; }
        public Nullable<decimal> q_d_clsp { get; set; }
        public Nullable<decimal> q_d_sys { get; set; }
        public Nullable<decimal> q_d_cv { get; set; }
        public Nullable<decimal> q_d_thin { get; set; }
        public Nullable<decimal> q_d_scv { get; set; }
        public Nullable<decimal> q_d_thick { get; set; }
        public Nullable<decimal> q_d_ipi { get; set; }
        public Nullable<decimal> q_d_tpi { get; set; }
        public Nullable<decimal> q_d_neps200 { get; set; }
        public Nullable<decimal> q_d_neps280 { get; set; }
        public Nullable<bool> q_m_ac { get; set; }
        public Nullable<bool> q_m_u { get; set; }
        public Nullable<bool> q_m_clsp { get; set; }
        public Nullable<bool> q_m_sys { get; set; }
        public Nullable<int> q_status_index { get; set; }
    }
}
