//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_register
    {
        public long r_id { get; set; }
        public Nullable<System.Guid> r_guid { get; set; }
        public Nullable<System.DateTime> r_indate { get; set; }
        public string r_mail { get; set; }
        public string r_phone { get; set; }
        public Nullable<bool> r_regok { get; set; }
        public Nullable<bool> r_reset { get; set; }
    }
}
