//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_receiptNotificiation_items
    {
        public int ri_id { get; set; }
        public System.Guid ri_guid { get; set; }
        public string ri_name { get; set; }
        public string ri_monetarySystem { get; set; }
        public Nullable<decimal> ri_unitPrice { get; set; }
        public string ri_amount { get; set; }
        public Nullable<decimal> ri_sum { get; set; }
        public string ri_remark { get; set; }
    }
}
