//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_receiptNotification
    {
        public int r_id { get; set; }
        public System.Guid r_guid { get; set; }
        public string o_code { get; set; }
        public System.Guid o_guid { get; set; }
        public string r_ip { get; set; }
        public string r_port { get; set; }
        public System.DateTime r_indate { get; set; }
        public string r_client { get; set; }
        public string r_organizer { get; set; }
        public string r_BLNo { get; set; }
        public string r_orderNo { get; set; }
        public string r_invoceNo { get; set; }
        public string r_productName { get; set; }
        public int r_guiCount { get; set; }
        public string r_grossWeight { get; set; }
        public string r_packageNumber { get; set; }
        public string r_operator { get; set; }
        public string r_filepath { get; set; }
        public Nullable<System.DateTime> r_creationDate { get; set; }
    }
}
