//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_savedec_log
    {
        public long di_id { get; set; }
        public Nullable<System.Guid> di_guid { get; set; }
        public Nullable<System.DateTime> di_indate { get; set; }
        public System.Guid di_orderid { get; set; }
        public string di_op { get; set; }
        public Nullable<System.Guid> di_opid { get; set; }
        public string di_opip { get; set; }
        public string di_opport { get; set; }
        public string di_sendurl { get; set; }
        public string di_interface { get; set; }
        public bool di_ok { get; set; }
        public string di_return { get; set; }
        public Nullable<System.DateTime> di_returndate { get; set; }
    }
}
