//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sheetPic
    {
        public long pic_id { get; set; }
        public Nullable<System.Guid> pic_guid { get; set; }
        public Nullable<System.DateTime> pic_indate { get; set; }
        public System.Guid pic_oid { get; set; }
        public string pic_activity { get; set; }
        public string pic_inputer { get; set; }
        public string pic_inputerCompany { get; set; }
        public System.Guid pic_inputerid { get; set; }
        public System.Guid pic_session { get; set; }
        public string pic_file { get; set; }
        public Nullable<bool> pic_check { get; set; }
    }
}
