//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sms_log
    {
        public long sms_id { get; set; }
        public Nullable<System.Guid> sms_guid { get; set; }
        public Nullable<System.DateTime> sms_indate { get; set; }
        public string sms_ip { get; set; }
        public string sms_phone { get; set; }
        public string sms_msg { get; set; }
        public bool sms_ok { get; set; }
        public string sms_return { get; set; }
        public string sms_interface { get; set; }
    }
}
