//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_systemSetting
    {
        public int s_id { get; set; }
        public Nullable<System.Guid> s_guid { get; set; }
        public Nullable<System.DateTime> s_indate { get; set; }
        public string s_inputer { get; set; }
        public System.Guid s_inpuerid { get; set; }
        public string s_name { get; set; }
        public string s_type { get; set; }
        public string s_setting { get; set; }
    }
}
