//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_vat
    {
        public int v_id { get; set; }
        public System.Guid v_guid { get; set; }
        public System.Guid o_guid { get; set; }
        public string o_code { get; set; }
        public string v_ip { get; set; }
        public string v_port { get; set; }
        public System.DateTime v_indate { get; set; }
        public string v_logisticsCompany { get; set; }
        public string v_incomeSystem { get; set; }
        public System.DateTime v_time { get; set; }
        public string v_No { get; set; }
        public string v_office { get; set; }
        public string v_project { get; set; }
        public string v_budgetaryLevel { get; set; }
        public string v_recipientTreasury { get; set; }
        public string v_payName { get; set; }
        public string v_payAccount { get; set; }
        public string v_bank { get; set; }
        public decimal v_rmbMoney { get; set; }
        public string v_exchangeRate { get; set; }
        public string v_rmbUMoney { get; set; }
        public string v_unitNo { get; set; }
        public string v_declarationNo { get; set; }
        public string v_approvalNo { get; set; }
        public string v_transportNo { get; set; }
        public string v_deadline { get; set; }
        public string v_loadingNo { get; set; }
        public string v_GBCode { get; set; }
        public string v_EPTransaction { get; set; }
        public string v_filepath { get; set; }
    }
}
