//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wantbuy_collect
    {
        public long bf_id { get; set; }
        public Nullable<System.Guid> bf_guid { get; set; }
        public string bf_own { get; set; }
        public string bf_ownCom { get; set; }
        public System.Guid bf_ownId { get; set; }
        public System.DateTime bf_indate { get; set; }
        public System.Guid bf_wbId { get; set; }
    }
}
