//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wantbuy_offer
    {
        public long of_id { get; set; }
        public Nullable<System.Guid> of_guid { get; set; }
        public Nullable<System.DateTime> of_indate { get; set; }
        public System.Guid of_wbId { get; set; }
        public decimal of_price { get; set; }
        public System.Guid of_productId { get; set; }
        public string of_status { get; set; }
    }
}
