//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_wantbuy
    {
        public long b_id { get; set; }
        public System.Guid b_guid { get; set; }
        public Nullable<System.DateTime> b_indate { get; set; }
        public Nullable<System.DateTime> b_modidate { get; set; }
        public string b_requestor { get; set; }
        public System.Guid b_requestorID { get; set; }
        public string b_chengfen { get; set; }
        public string b_shazhi { get; set; }
        public string b_gushu { get; set; }
        public string b_chengshashebei { get; set; }
        public string b_shumiangongyi { get; set; }
        public string b_shiyongfanwei { get; set; }
        public string b_pinji { get; set; }
        public string b_peimian { get; set; }
        public string b_chandi { get; set; }
        public string b_zhizaoyongtu { get; set; }
        public string b_zuizhongchanpin { get; set; }
        public string b_mubiaoshichang { get; set; }
        public string b_guitype { get; set; }
        public int b_amount { get; set; }
        public string b_gongyingType { get; set; }
        public string b_jiaoyiType { get; set; }
        public System.DateTime b_youxiaoqi { get; set; }
        public string b_status { get; set; }
    }
}
