//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_workflow_setting
    {
        public int ws_id { get; set; }
        public string ws_name { get; set; }
        public string ws_caption { get; set; }
        public string ws_setting { get; set; }
        public string ws_inputer { get; set; }
        public string ws_inputerid { get; set; }
        public Nullable<System.DateTime> ws_indate { get; set; }
    }
}
