//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_workflow
    {
        public long wf_id { get; set; }
        public string wf_guid { get; set; }
        public string wf_flcaption { get; set; }
        public string wf_note { get; set; }
        public string wf_dutyname { get; set; }
        public string wf_dutyusrname { get; set; }
        public string wf_dutyrole { get; set; }
        public string wf_dutyguid { get; set; }
        public string wf_owner { get; set; }
        public string wf_ownerid { get; set; }
        public string wf_lastop { get; set; }
        public string wf_lastopid { get; set; }
        public string wf_lastnote { get; set; }
        public string wf_lastresult { get; set; }
        public Nullable<System.DateTime> wf_lasttime { get; set; }
        public string wf_object { get; set; }
        public string wf_stat { get; set; }
    }
}
