//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_LcRateClients
    {
        public long r_id { get; set; }
        public Nullable<System.Guid> r_guid { get; set; }
        public Nullable<System.DateTime> r_indate { get; set; }
        public string r_ownCom { get; set; }
        public string r_ownComEng { get; set; }
        public System.Guid r_ownComId { get; set; }
        public string r_clientCom { get; set; }
        public string r_clientComEng { get; set; }
        public System.Guid r_clientComId { get; set; }
        public decimal r_rate { get; set; }
        public string r_memo { get; set; }
        public string r_inputer { get; set; }
        public System.Guid r_inputerid { get; set; }
        public Nullable<int> r_sort { get; set; }
        public int e_id { get; set; }
        public Nullable<System.Guid> e_guid { get; set; }
        public Nullable<System.DateTime> e_regdate { get; set; }
        public string e_regip { get; set; }
        public string e_logmail { get; set; }
        public Nullable<bool> e_logmailChk { get; set; }
        public string e_logphone { get; set; }
        public Nullable<bool> e_logphoneChk { get; set; }
        public string e_role1 { get; set; }
        public string e_role2 { get; set; }
        public string e_role3 { get; set; }
        public string e_password { get; set; }
        public string e_realname { get; set; }
        public string e_realnameEng { get; set; }
        public string e_gender { get; set; }
        public string e_pic { get; set; }
        public string e_grade { get; set; }
        public string e_department { get; set; }
        public string e_official { get; set; }
        public string e_company { get; set; }
        public string e_comEng { get; set; }
        public string e_brand { get; set; }
        public string e_brandEng { get; set; }
        public string e_region { get; set; }
        public string e_zhucehao { get; set; }
        public string e_zhizhaopic { get; set; }
        public string e_zizhipic2 { get; set; }
        public string e_zizhipic3 { get; set; }
        public string e_changqupic { get; set; }
        public string e_add { get; set; }
        public string e_addEng { get; set; }
        public Nullable<long> e_rank { get; set; }
        public string e_emblem { get; set; }
        public string e_bank { get; set; }
        public string e_bankacc { get; set; }
        public string e_bankadd { get; set; }
        public string e_banktel { get; set; }
        public string e_bankfax { get; set; }
        public string e_bankswift { get; set; }
        public string e_bankBeneficiary { get; set; }
        public string e_bankAddress { get; set; }
        public string e_bankComTel { get; set; }
        public string e_bankComFax { get; set; }
        public string e_posBankName { get; set; }
        public string e_posBankAcc { get; set; }
        public string e_posAccName { get; set; }
        public Nullable<decimal> e_posCreditLimit { get; set; }
        public string e_zhusuo { get; set; }
        public string e_zhizhaoname { get; set; }
        public string e_postcode { get; set; }
        public string e_farendaibiao { get; set; }
        public string e_zhuceziben { get; set; }
        public string e_shishouziben { get; set; }
        public string e_gongsileixing { get; set; }
        public string e_jingyingfanwei { get; set; }
        public Nullable<System.DateTime> e_chengliriqi { get; set; }
        public string e_yingyeqixian { get; set; }
        public string e_mobile { get; set; }
        public string e_tel { get; set; }
        public string e_fax { get; set; }
        public string e_mail { get; set; }
        public string e_website { get; set; }
        public string e_QQ { get; set; }
        public Nullable<byte> e_orderby { get; set; }
        public Nullable<long> e_visit { get; set; }
        public Nullable<int> e_login { get; set; }
        public Nullable<System.DateTime> e_lasttime { get; set; }
        public string e_lastip { get; set; }
        public Nullable<bool> e_srv { get; set; }
        public Nullable<bool> e_lock { get; set; }
        public string e_about { get; set; }
        public Nullable<bool> e_tuijian { get; set; }
        public Nullable<int> e_status { get; set; }
        public string e_statusText { get; set; }
        public string e_reason { get; set; }
        public Nullable<int> e_sellCount { get; set; }
    }
}
