//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_seller
    {
        public long o_id { get; set; }
        public Nullable<System.Guid> o_guid { get; set; }
        public Nullable<System.Guid> o_wfid { get; set; }
        public string o_code { get; set; }
        public Nullable<System.DateTime> o_signDate { get; set; }
        public System.DateTime o_indate { get; set; }
        public Nullable<System.DateTime> o_completionDate { get; set; }
        public string o_own { get; set; }
        public string o_ownParty { get; set; }
        public string o_ownCompany { get; set; }
        public string o_ownCompanyEng { get; set; }
        public System.Guid o_ownid { get; set; }
        public string o_supplierParty { get; set; }
        public string o_supplierCompany { get; set; }
        public string o_supplierCompanyEng { get; set; }
        public string o_supplierBeneficiary { get; set; }
        public System.Guid o_supplierid { get; set; }
        public string o_platParty { get; set; }
        public string o_platCompany { get; set; }
        public string o_platCompanyEng { get; set; }
        public Nullable<System.Guid> o_platid { get; set; }
        public string o_lcmakerParty { get; set; }
        public string o_lcCompany { get; set; }
        public string o_lcCompanyEng { get; set; }
        public Nullable<System.Guid> o_lcid { get; set; }
        public Nullable<System.Guid> o_lcSetId { get; set; }
        public Nullable<decimal> o_lcRate { get; set; }
        public System.Guid o_productid { get; set; }
        public string o_jiaohuodate { get; set; }
        public int o_amunt { get; set; }
        public decimal o_weight { get; set; }
        public decimal o_uintprice { get; set; }
        public decimal o_price { get; set; }
        public Nullable<decimal> o_exchange { get; set; }
        public Nullable<decimal> o_exchange_pay { get; set; }
        public Nullable<decimal> o_uintpriceOld { get; set; }
        public Nullable<decimal> o_priceOld { get; set; }
        public Nullable<decimal> o_earnest { get; set; }
        public Nullable<decimal> o_balance { get; set; }
        public Nullable<decimal> o_freight { get; set; }
        public Nullable<bool> o_selfFreight { get; set; }
        public string o_freightmemo { get; set; }
        public string o_freightSheet { get; set; }
        public string o_freightcarrier { get; set; }
        public Nullable<System.Guid> o_freightcarrierId { get; set; }
        public string o_freightTruck { get; set; }
        public string o_freightDriver { get; set; }
        public string o_freightDriverPhone { get; set; }
        public Nullable<System.DateTime> o_freightArrive { get; set; }
        public string o_cif { get; set; }
        public string o_sh_sheng { get; set; }
        public string o_sh_shi { get; set; }
        public string o_sh_qu { get; set; }
        public string o_sh_jiedao { get; set; }
        public string o_sh_lxr { get; set; }
        public string o_sh_mob { get; set; }
        public string o_sh_pc { get; set; }
        public string o_sh_telqu { get; set; }
        public string o_sh_tel { get; set; }
        public string o_sh_telfen { get; set; }
        public string o_i_name { get; set; }
        public string o_i_taxcode { get; set; }
        public string o_i_bank { get; set; }
        public string o_i_bankno { get; set; }
        public string o_i_add { get; set; }
        public string o_i_tel { get; set; }
        public string o_memo { get; set; }
        public string o_shippic { get; set; }
        public string o_earnestpic { get; set; }
        public string o_balancepic { get; set; }
        public string o_lcpic { get; set; }
        public string o_reason { get; set; }
        public string o_recmsg { get; set; }
        public Nullable<int> o_stat { get; set; }
        public string o_statText { get; set; }
        public string o_statSeller { get; set; }
        public string o_statBuyer { get; set; }
        public Nullable<bool> o_tuijian { get; set; }
        public Nullable<bool> o_chk_agree_pay { get; set; }
        public Nullable<bool> o_chk_agree_agent { get; set; }
        public Nullable<bool> o_chk_qc { get; set; }
        public Nullable<System.Guid> o_qc_id { get; set; }
        public Nullable<System.Guid> o_pay_id { get; set; }
        public string o_lc_type { get; set; }
        public string o_lc_port { get; set; }
        public Nullable<int> o_lc_days { get; set; }
        public string o_lc_style { get; set; }
        public int e_id { get; set; }
        public Nullable<System.Guid> e_guid { get; set; }
        public Nullable<System.DateTime> e_regdate { get; set; }
        public string e_regip { get; set; }
        public string e_logmail { get; set; }
        public Nullable<bool> e_logmailChk { get; set; }
        public string e_logphone { get; set; }
        public Nullable<bool> e_logphoneChk { get; set; }
        public string e_role1 { get; set; }
        public string e_role2 { get; set; }
        public string e_role3 { get; set; }
        public string e_password { get; set; }
        public string e_realname { get; set; }
        public string e_realnameEng { get; set; }
        public string e_gender { get; set; }
        public string e_pic { get; set; }
        public string e_grade { get; set; }
        public string e_department { get; set; }
        public string e_official { get; set; }
        public string e_company { get; set; }
        public string e_comEng { get; set; }
        public string e_brand { get; set; }
        public string e_brandEng { get; set; }
        public string e_region { get; set; }
        public string e_zhucehao { get; set; }
        public string e_zhizhaopic { get; set; }
        public string e_zizhipic2 { get; set; }
        public string e_zizhipic3 { get; set; }
        public string e_changqupic { get; set; }
        public string e_add { get; set; }
        public string e_addEng { get; set; }
        public Nullable<long> e_rank { get; set; }
        public string e_emblem { get; set; }
        public string e_bank { get; set; }
        public string e_bankacc { get; set; }
        public string e_bankadd { get; set; }
        public string e_banktel { get; set; }
        public string e_bankfax { get; set; }
        public string e_bankswift { get; set; }
        public string e_bankBeneficiary { get; set; }
        public string e_bankAddress { get; set; }
        public string e_bankComTel { get; set; }
        public string e_bankComFax { get; set; }
        public string e_posBankName { get; set; }
        public string e_posBankAcc { get; set; }
        public string e_posAccName { get; set; }
        public Nullable<decimal> e_posCreditLimit { get; set; }
        public string e_zhusuo { get; set; }
        public string e_zhizhaoname { get; set; }
        public string e_postcode { get; set; }
        public string e_farendaibiao { get; set; }
        public string e_zhuceziben { get; set; }
        public string e_shishouziben { get; set; }
        public string e_gongsileixing { get; set; }
        public string e_jingyingfanwei { get; set; }
        public Nullable<System.DateTime> e_chengliriqi { get; set; }
        public string e_yingyeqixian { get; set; }
        public string e_mobile { get; set; }
        public string e_tel { get; set; }
        public string e_fax { get; set; }
        public string e_mail { get; set; }
        public string e_website { get; set; }
        public string e_QQ { get; set; }
        public Nullable<byte> e_orderby { get; set; }
        public Nullable<long> e_visit { get; set; }
        public Nullable<int> e_login { get; set; }
        public Nullable<System.DateTime> e_lasttime { get; set; }
        public string e_lastip { get; set; }
        public Nullable<bool> e_srv { get; set; }
        public Nullable<bool> e_lock { get; set; }
        public string e_about { get; set; }
        public Nullable<bool> e_tuijian { get; set; }
        public Nullable<int> e_status { get; set; }
        public string e_statusText { get; set; }
        public string e_reason { get; set; }
        public Nullable<int> e_sellCount { get; set; }
        public string e_pushSetting { get; set; }
        public Nullable<bool> e_agree_agent { get; set; }
        public string e_check_fw { get; set; }
    }
}
