//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_wf_log
    {
        public long wg_id { get; set; }
        public System.Guid wg_guid { get; set; }
        public System.Guid wg_wfid { get; set; }
        public string wg_op { get; set; }
        public System.Guid wg_opid { get; set; }
        public string wg_note { get; set; }
        public string wg_result { get; set; }
        public string wg_usrmsg { get; set; }
        public string wg_sheetlink { get; set; }
        public string wg_sheetname { get; set; }
        public System.DateTime wg_time { get; set; }
        public string wg_roles { get; set; }
        public string e_company { get; set; }
        public string e_comEng { get; set; }
        public string e_realname { get; set; }
        public string e_realnameEng { get; set; }
        public string wg_opip { get; set; }
    }
}
