//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rock.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YarnTradeEntities : DbContext
    {
        public YarnTradeEntities()
            : base("name=YarnTradeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EAction> EAction { get; set; }
        public virtual DbSet<EActionFormConfig> EActionFormConfig { get; set; }
        public virtual DbSet<EActionPushConfig> EActionPushConfig { get; set; }
        public virtual DbSet<EActionPushDynamicRole> EActionPushDynamicRole { get; set; }
        public virtual DbSet<EActionPushMsgParams> EActionPushMsgParams { get; set; }
        public virtual DbSet<EActionShowConfig> EActionShowConfig { get; set; }
        public virtual DbSet<EActionSwitch> EActionSwitch { get; set; }
        public virtual DbSet<EInstance> EInstance { get; set; }
        public virtual DbSet<EInstanceAudit> EInstanceAudit { get; set; }
        public virtual DbSet<EInstanceLog> EInstanceLog { get; set; }
        public virtual DbSet<EInstanceProgress> EInstanceProgress { get; set; }
        public virtual DbSet<EPushGroup> EPushGroup { get; set; }
        public virtual DbSet<EPushGroupUser> EPushGroupUser { get; set; }
        public virtual DbSet<EState> EState { get; set; }
        public virtual DbSet<EStateShowConfig> EStateShowConfig { get; set; }
        public virtual DbSet<EWorkflow> EWorkflow { get; set; }
        public virtual DbSet<EWorkflowUse> EWorkflowUse { get; set; }
        public virtual DbSet<t_ad> t_ad { get; set; }
        public virtual DbSet<t_ad_setting> t_ad_setting { get; set; }
        public virtual DbSet<t_address> t_address { get; set; }
        public virtual DbSet<t_agreement_agent> t_agreement_agent { get; set; }
        public virtual DbSet<t_agreement_pay> t_agreement_pay { get; set; }
        public virtual DbSet<t_anonymous> t_anonymous { get; set; }
        public virtual DbSet<t_app_log> t_app_log { get; set; }
        public virtual DbSet<t_buglst> t_buglst { get; set; }
        public virtual DbSet<t_Channel> t_Channel { get; set; }
        public virtual DbSet<t_codeIndex> t_codeIndex { get; set; }
        public virtual DbSet<t_customs_fee> t_customs_fee { get; set; }
        public virtual DbSet<t_DicRegion> t_DicRegion { get; set; }
        public virtual DbSet<t_dict> t_dict { get; set; }
        public virtual DbSet<t_emblem_setting> t_emblem_setting { get; set; }
        public virtual DbSet<t_enterprise> t_enterprise { get; set; }
        public virtual DbSet<t_event_signup> t_event_signup { get; set; }
        public virtual DbSet<t_events> t_events { get; set; }
        public virtual DbSet<t_exchange_records> t_exchange_records { get; set; }
        public virtual DbSet<t_FriendGroup> t_FriendGroup { get; set; }
        public virtual DbSet<t_friendIndex> t_friendIndex { get; set; }
        public virtual DbSet<t_guestBook> t_guestBook { get; set; }
        public virtual DbSet<t_importdeclaration> t_importdeclaration { get; set; }
        public virtual DbSet<t_importdeclaration_items> t_importdeclaration_items { get; set; }
        public virtual DbSet<t_importtariff> t_importtariff { get; set; }
        public virtual DbSet<t_importtariff_items> t_importtariff_items { get; set; }
        public virtual DbSet<t_inbox> t_inbox { get; set; }
        public virtual DbSet<t_Inquiry_Apply> t_Inquiry_Apply { get; set; }
        public virtual DbSet<t_Inquiry_ApplyAttr> t_Inquiry_ApplyAttr { get; set; }
        public virtual DbSet<t_Inquiry_Collection> t_Inquiry_Collection { get; set; }
        public virtual DbSet<t_Inquiry_Config> t_Inquiry_Config { get; set; }
        public virtual DbSet<t_Inquiry_Offer> t_Inquiry_Offer { get; set; }
        public virtual DbSet<t_Inquiry_SerialNumber> t_Inquiry_SerialNumber { get; set; }
        public virtual DbSet<t_invoice> t_invoice { get; set; }
        public virtual DbSet<t_lc_Rate> t_lc_Rate { get; set; }
        public virtual DbSet<t_lc_setting> t_lc_setting { get; set; }
        public virtual DbSet<t_lc_Sheet> t_lc_Sheet { get; set; }
        public virtual DbSet<t_log> t_log { get; set; }
        public virtual DbSet<t_message> t_message { get; set; }
        public virtual DbSet<t_messageJobs> t_messageJobs { get; set; }
        public virtual DbSet<t_msg_sc> t_msg_sc { get; set; }
        public virtual DbSet<t_online> t_online { get; set; }
        public virtual DbSet<t_orders> t_orders { get; set; }
        public virtual DbSet<t_OrderTest> t_OrderTest { get; set; }
        public virtual DbSet<t_page> t_page { get; set; }
        public virtual DbSet<t_pay_info> t_pay_info { get; set; }
        public virtual DbSet<t_pay_log> t_pay_log { get; set; }
        public virtual DbSet<t_Permission> t_Permission { get; set; }
        public virtual DbSet<t_platform_collectmenu> t_platform_collectmenu { get; set; }
        public virtual DbSet<t_platform_menu> t_platform_menu { get; set; }
        public virtual DbSet<t_platform_menutype> t_platform_menutype { get; set; }
        public virtual DbSet<t_product> t_product { get; set; }
        public virtual DbSet<t_product_snap> t_product_snap { get; set; }
        public virtual DbSet<t_Qc> t_Qc { get; set; }
        public virtual DbSet<t_receiptNotification> t_receiptNotification { get; set; }
        public virtual DbSet<t_receiptNotificiation_items> t_receiptNotificiation_items { get; set; }
        public virtual DbSet<t_RecentContact> t_RecentContact { get; set; }
        public virtual DbSet<t_register> t_register { get; set; }
        public virtual DbSet<t_Rights> t_Rights { get; set; }
        public virtual DbSet<t_RoleList> t_RoleList { get; set; }
        public virtual DbSet<t_savedec_log> t_savedec_log { get; set; }
        public virtual DbSet<t_sheetPic> t_sheetPic { get; set; }
        public virtual DbSet<t_sms_log> t_sms_log { get; set; }
        public virtual DbSet<t_systemSetting> t_systemSetting { get; set; }
        public virtual DbSet<t_vat> t_vat { get; set; }
        public virtual DbSet<t_vat_items> t_vat_items { get; set; }
        public virtual DbSet<t_wantbuy> t_wantbuy { get; set; }
        public virtual DbSet<t_wantbuy_collect> t_wantbuy_collect { get; set; }
        public virtual DbSet<t_wantbuy_offer> t_wantbuy_offer { get; set; }
        public virtual DbSet<t_workflow> t_workflow { get; set; }
        public virtual DbSet<t_workflow_log> t_workflow_log { get; set; }
        public virtual DbSet<t_workflow_setting> t_workflow_setting { get; set; }
        public virtual DbSet<t_sensitiveWord> t_sensitiveWord { get; set; }
        public virtual DbSet<v_buyer> v_buyer { get; set; }
        public virtual DbSet<v_friends> v_friends { get; set; }
        public virtual DbSet<v_lcmaker> v_lcmaker { get; set; }
        public virtual DbSet<v_LcRateClients> v_LcRateClients { get; set; }
        public virtual DbSet<v_LcRateOwn> v_LcRateOwn { get; set; }
        public virtual DbSet<v_Licence> v_Licence { get; set; }
        public virtual DbSet<v_orders> v_orders { get; set; }
        public virtual DbSet<v_platform> v_platform { get; set; }
        public virtual DbSet<v_Qc> v_Qc { get; set; }
        public virtual DbSet<v_seller> v_seller { get; set; }
        public virtual DbSet<v_wf_log> v_wf_log { get; set; }
    }
}
